export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const WARN_MESSAGE = "WARN_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const INFO_MESSAGE = "INFO_MESSAGE";

export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER'