// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:0a020f82-5f0d-420d-98ca-4f93562fcc7f',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'arvindlaxan-hosting-mobilehub-1292351267',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1wa87msz8wlk0.cloudfront.net',
    'aws_mobile_analytics_app_id': '9887ee84e76f45898db2fac049039699',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e04e8e7f-7d33-45d3-bfda-22e418a641ef',
    'aws_project_name': 'Arvind Laxan',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'arvindlaxan-mobilehub-1292351267',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_46u1Omqph',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': 'r38i6atmu78ca4m73lc5p91ap',
}

export default awsmobile;
