// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-2:f0926032-43fe-4d89-b50a-48d2f93e8cfa',
    'aws_cognito_region': 'ap-southeast-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'lexcen-hosting-mobilehub-1007065480',
    'aws_content_delivery_bucket_region': 'ap-southeast-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd32vi6xvom11fg.cloudfront.net',
    'aws_mobile_analytics_app_id': '710153a8f17f4fbc8feffd284ffb55c6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f1ddb64f-4ebc-4be5-b5a8-94bc71624bc8',
    'aws_project_name': 'lexcen',
    'aws_project_region': 'ap-southeast-2',
    'aws_resource_name_prefix': 'lexcen-mobilehub-1007065480',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-2_udRB0J4V7',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1ic41alac8oo2c0mo0hjmk77p7',
}

export default awsmobile;
